theme: jekyll-theme-slate
title: Instruções
description: Este side descreve como está o site da miminhos customizado. Estas instruções servem de referência para futuras alterações ao site. Ou para futuros sites, baseados na miminhos.